### ISSUE TITLE
Install via app name / use tab completion to get app ID from name

### ISSUE THREAD

**Issue by mcandre** [mas-cli/mas#109]
For convenience, could `mas install "Some Cool App"` automatically lookup the numerical identifier? Kinda stinks that users are expected to manage this information on behalf of mas.

**Comment by dotCipher** [comment]
Agreed, functionality like that would be awesome.

**Comment by mcandre** [comment]
Go ahead and lookup the ID when the user searches for an application, and then invoke the install phase using that ID. Do this on behalf of the user.

**Comment by brianmorton** [comment]
This is a little more complicated in many cases, with respect to @mcandre's comment in particular. Search isn't deterministic, as sometimes more than one result will come back.
```
$ mas search quip
1003160018 Quip 
1002623276 Quiplash
```

So even if you wanted to install quip here, you might run into unexpected situations.

**Comment by dentarg** [comment]
[v1.4.0](https://github.com/mas-cli/mas/releases/tag/v1.4.0) has implemented this with the `mas lucky` command (https://github.com/mas-cli/mas/pull/88)

**Comment by mcandre** [comment]
@brianmorton This is why an exact name should be used.

**Comment by phatblat** [comment]
#100 changed the `upgrade` command to work with app names or IDs. I agree that `install` should work off app names with IDs also supported for backwards compatibility.

One potential complication is the fact that app names in the app store can change and also can sometimes be quite long. It would be nice if there were a way to have unique tokens for each app like what [Homebrew cask](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#searching-for-casks) uses. But, I'm not sure how that could be managed as `mas` doesn't control the app name data. In any case, we could support exact app name matches without much work.

**Comment by bgibson72** [comment]
Is there a way to install previous versions of macOS?  If I search the app store with `mas search`, I get the latest version which I do not want.  I'd like to grab 10.13.3 or even 10.13.0 rather than 10.13.5.  Thanks!

**Comment by phatblat** [comment]
@bgibson72 Looks like there are many updaters on the [Apple Support Downloads](https://support.apple.com/downloads/macos) site. However, I can't tell if these contain a full installer or require that a previous version of macOS already be installed that they simply "update".

**Comment by ludwigschubert** [comment]
@brianmorton how would you feel about presenting an interactive list of choices in such cases?

**Comment by phatblat** [comment]
That’s an interesting idea. If the search string results in exact one result, install it. Otherwise stop and present a list.

**Comment by brianmorton** [comment]
> One potential complication is the fact that app names in the app store can change and also can sometimes be quite long. It would be nice if there were a way to have unique tokens for each app like what Homebrew cask uses. But, I'm not sure how that could be managed as `mas` doesn't control the app name data. In any case, we could support exact app name matches without much work.

Cask gets around this be acting as a middleman (we provide tokenization rules and name apps in a repeatable fashion so we always know what a given "pretty" name will be when tokenized).

> @brianmorton how would you feel about presenting an interactive list of choices in such cases?

I generally find interactive lists to be great UX (which is my background), however most people that opt to use `mas` switched from a GUI (eg. the app store) to the commandline for a reason - most likely some element of scriptability or automation. Interactive lists can pose challenges to that.

> That’s an interesting idea. If the search string results in exact one result, install it. Otherwise stop and present a list.

If you wanted to move forward with this, my suggestion would be to introduce tokenization (like cask) so that names would be tokenized and unique. If that is not palatable, I would then say do the install if the search result is deterministic (eg. the same functionality as `lucky`), or abort with an error exit code and a list of possible options (eg. `did you mean quip (1003160018), quiplash (1002623276 )`, etc.)

In my opinion, that is how it would be resolved if this was an issue at hbc, as they strive to make things somewhat backwards compatible (eg. not break existing installations or people using it in a scripted/automated way) while introducing new features.

**Comment by phatblat** [comment]
@brianmorton regarding tokenization, App Store and iTunes URLs support [short links](https://developer.apple.com/library/archive/qa/qa1633/_index.html#//apple_ref/doc/uid/DTS40009414-CH1-SOURCECODE1) for app names with clearly defined rules for building the URL from an app name. `mas` currently uses the [iTunes Search API](https://affiliate.itunes.apple.com/resources/documentation/itunes-store-web-service-search-api/) for `search`, `lucky` and `info` commands. I suspect these two Apple systems work with the same data, but I haven't seen short links show up in search results so I don't know how `mas` could confirm that a given token actually corresponds to a specific app because the ID is what's used to initiate the install.

I've been wanting to do some reverse engineering to see what the native macOS API for the App Store looks like because that might open up new possibilities.

I agree that an interactive menu would be problematic for scripting and automation, so if that were added there would either need to be a way to opt in or out (depending on which is used more, I don't have any stats to help decide).

**Comment by phatblat** [comment]
The app token to app ID mapping could certainly be constructed and stored somewhere, but my worry since the App Store is continuously changing through Apple's processes, there would be lots of issues trying to keep this data up-to-date. I'm hoping we can find a solution that doesn't require maintain a separate database which will get stale quickly.

**Comment by rgoldberg** [comment]
This functionality is already supported by `mas lucky`.

Convenient lookup of deterministic app IDs for any command that accepts ID arguments should be performed by shell tab completion using `mas search <current tabbed token>` to populate the completion list with each matching app name shown besides its app ID.

Once this has been provided for all supported shells, maybe `mas lucky` should be removed.

**Comment by rgoldberg** [comment]
`mas` commands should accept bundle IDs anywhere app IDs are accepted as command-line arguments.

Bundle IDs should be deterministically unique (unlike app names)

Bundle IDs are more descriptive of the app than app IDs, so if you copy & paste the wrong bundle ID or have a typo in one, it's much more obvious.

In many cases, bundle IDs could be used instead of app IDs without connecting to Apple servers to find the app ID from the bundle ID. If there are ever commands where we cannot determine the app ID from the bundle ID without connecting to Apple servers, we can either look for endpoints that accept bundle IDs instead of app IDs, or we can just send an extra query to Apple servers for the info (if Apple provides such a deterministic endpoint). If not provided, then certain commands might only support app IDs, not bundle IDs.

**Comment by rgoldberg** [comment]
Closing in favor of #678
