### ISSUE TITLE
Output Apple Account for app

### ISSUE THREAD

**Issue by RickCogley** [mas-cli/mas#22]
Hello - does your app allow people to find out which apple id an app was installed with? 

In a company environment, sometimes upgrades are a pain, because different apple Ids were used. 

I'm looking for a way to run a script on a computer, to get a list of the MAS apps, but showing which apple id was used for the install. 

Is such a think possible, would you happen to know?

**Comment by argon** [comment]
Not with the interfaces that MAS uses. I don't think that Apple stores readable identifiers with installed applications, for security reasons.

**Comment by RickCogley** [comment]
@argon thanks very much. Yes, it appears that that info is just not available.

**Comment by timsutton** [comment]
This trick used to be possible:

http://magervalp.github.io/2013/03/19/poking-around-in-masreceipts.html

But in the past couple years there have been changes that no longer make this possible. I believe it's still possible to tell whether an ID is the _same_ across several apps because of a consistent identifier somewhere, but it doesn't actually expose the Apple ID in plaintext.
