### ISSUE TITLE
Is it possible to install from cache?

### ISSUE THREAD

**Issue by roeybiran** [mas-cli/mas#224]
Hi, thanks for this wonderful utility!

I was wondering if it would be possible to just download all App Store apps in advance, then install it from cache later on? This could be mighty useful when setting up a new machine — it would be make the whole process much speedier.

Note: this functionality is achieved in `brew` using the `brew fetch` command.

Thanks!

**Comment by phatblat** [comment]
Unfortunately, this does not seem possible. `mas` is really just a hack that taps into some App Store functionality. The "install" action actually triggers a "[purchase](https://www.deque.com/blog/reflecting-on-deque-microsoft-collaboration/)" and then monitors the resulting download.

Right now, this "purchase" only works if you've previously purchased the app in question. I'm researching whether we can change this for macOS installers in #144 since they don't require a login through the GUI app.

The only workaround for this might benefit installation across multiple macs: set up [content caching](https://www.idownloadblog.com/2018/07/17/howto-mac-content-caching/) on one Mac and make sure all Macs are on the same network subnet. The first download of an app would take the normal time, but it would get saved in a cache on the configured Mac. Subsequent downloads of the same app would use the local Mac cache instead of redownloading the app from the cloud.
