### ISSUE TITLE
`outdated` & `upgrade` fail on Catalina

### ISSUE THREAD

**Issue by nottoseethesun** [mas-cli/mas#248]
I just updated to macOS Catalina, rebooted to be sure all works, but `mas "Xcode", id: 497799835` hangs.  It used to work fine in the past.  This command is being run from a `Brewfile`, via `brew bundle install`.

How to troubleshoot this?

**Comment by mangerlahn** [comment]
I have the same problem. It seems that the framework that mas-cli uses to gather all update information doesn't work anymore. There are new frameworks, `AppStoreFoundation` probably being the core of these. 

I spend a couple of days with that. Apple significantly upgraded the access control on this stuff. AppStoreFoundation delegates all calls to a process called appstoreagent, which checks the senders entitlements before it returns anything useful. That way Apple ensures that only processes can access update information that are intended to. I can't set these entitlements without disabling System Integrity Protection.

I currently have no idea how to continue with this, maybe someone here has a deeper understanding of how all that permission and entitlements stuff works and how we could build a system that can access the update information.

**Comment by phatblat** [comment]
The brew bundle command uses the `mas list` output to determine which apps are currently installed and `mas outdated` to figure out which apps are installed, but need to be updated. ([source](https://github.com/Homebrew/homebrew-bundle/blob/master/lib/bundle/mac_app_store_installer.rb#L14))

`outdated` was a bit flaky before Catalina, but based on the reports seems to be completely broken now, probably due to private frameworks changes as @mangerlahn mentioned.

As for debugging, you can add the `--verbose` flag to `brew bundle install`. This shows a progress part during the download part of the install.  I had it hang on older macOS installer app, so I removed that from my `Brewfile` to get around it.


```
brew bundle install --verbose
Using com.agilebits.onepassword7
Installing com.apple.InstallAssistant.Mavericks app. It is not currently installed.
###############--------------------------------------------- 26.0% Downloading
```

Note that the app names from the `list` command have been falling back to the bundle identifier on recent macOS versions (See #228).

```
...
Installing com.swiftClean app. It is not currently installed.
No downloads
Error: No downloads began
Installing com.swiftClean has failed!
Using com.tapbots.Tweetbot3Mac
Using com.tinyspeck.slackmacgap
Using de.milchimgemuesefach.Display-Menu
Using it.bloop.airmail2
Using net.shinyfrog.bear
Homebrew Bundle failed! 2 Brewfile dependencies failed to install.
```

Seems like there are several issues affecting the `brew bundle` support, but I'm curious if `--verbose` gives you more info. Also, if it is hanging on any apps can you try removing them from your `Brewfile` and report back which are causing problems?

**Comment by phatblat** [comment]
@mangerlahn How did you figure out the connection between [AppStoreFoundation](https://github.com/phatblat/macOSPrivateFrameworks/tree/10.15/PrivateFrameworks/AppStoreFoundation) and appstoreagent? Do you know what sort of [entitlements](https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/EnablingAppSandbox.html#//apple_ref/doc/uid/TP40011195-CH4-SW1) it's expecting, or did you just see an entitlements error? 

This is making me think that mas may need an [XPC service](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingXPCServices.html#//apple_ref/doc/uid/10000172i-SW6-SW1) in order to interact with these new system components.

I've got a Mac with SIP disabled specifically for this type of debugging. I'd love to see if I can get something working against these new APIs and then figure out if it's possible to use them on a Mac that still has SIP enabled.

**Comment by mangerlahn** [comment]
I took a look into both `AppStoreFoundation` and `appstoreagent`using the [Hopper Disassembler](https://www.hopperapp.com). You could write your own XPC service or use AppStoreFoundation as a wrapper directly. 

`appstoreagent ` evaluates the entitlements set on the caller of the XPC request using 
`SecTaskCopyValuesForEntitlements`. There are entitlements for basically every kind of request sent to appstoreagent.

To get a full list, I took a look at which entitlements are set on the Mac App Store app using 

    codesign -d --entitlements :- /System/Applications/App\ Store.app

There are many private entitlements set, but the most interesting are probably

    <key>com.apple.private.appstoreagent</key>
	<true/>
	<key>com.apple.private.appstored</key>
	<array>
		<string>Purchase</string>
		<string>Library</string>
		<string>Update</string>
		<string>PurchaseHistory</string>
		<string>IAPHistory</string>
	</array>

Once I set any custom entitlement, my app would crash immediately on launch (SIP on)..
I am curious to see whether you get this running with SIP turned off.

**Comment by phatblat** [comment]
@mangerlahn I'm finally getting back to digging into this and didn't find much in the [`AppStoreFoundation`](https://github.com/phatblat/macOSPrivateFrameworks/tree/e8ec27836c76771f1503aca8085a5cd19be24a4e/PrivateFrameworks/AppStoreFoundation) generated headers, however [`AppStoreDaemon`](https://github.com/phatblat/macOSPrivateFrameworks/tree/e8ec27836c76771f1503aca8085a5cd19be24a4e/PrivateFrameworks/AppStoreDaemon) has a ton of functionality. AppStoreDaemon is also the framework that contains the `appstoreagent` binary.

`/System/Library/PrivateFrameworks/AppStoreDaemon.framework/Support/appstoreagent`

One interesting find is [`-ASDSoftwareUpdatesStore reloadFromServerInBackgroundWithCompletionBlock:`](https://github.com/phatblat/macOSPrivateFrameworks/blob/e8ec27836c76771f1503aca8085a5cd19be24a4e/PrivateFrameworks/AppStoreDaemon/ASDSoftwareUpdatesStore.h#L24) which might come in handy for your Latest app  (and issues #247, #245)

**Comment by andrewcrook** [comment]
I have the same issue using mas directly from the command line. It first started with what were the  iWork apps  so numbers, pages , keynote etc not updating properly it said they were always out of date despite having the latest versions installed (same as #249 ). Then since  macOS 10.15.4 possibly 10.15.3 as well (cannot recall) the opposite it says **all** installed apps are the latest versions despite showing newer versions under the outdated command.

**Comment by andrewcrook** [comment]
Mind you I have noticed that [macupdater](https://www.corecode.io/macupdater/) picks up new versions of appstore apps. 

<img width="871" alt="image" src="https://user-images.githubusercontent.com/803618/82550794-02396f80-9b57-11ea-8179-3fb73dcc6fc1.png">

However, they rarely show under updates in the app store. 

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/803618/82550901-28f7a600-9b57-11ea-9a9f-16b70d3c5ca0.png">

Yet when I click on them under macupdater  it opens the appstore app at the apps page where there is an update button. 

<img width="1535" alt="image" src="https://user-images.githubusercontent.com/803618/82550988-4c225580-9b57-11ea-9dec-47a3282b528e.png">

If I leave them they do get install automatically eventually, I am not sure how long after.

So it seems to me that macOS does some sort of system maintenance scan and that the app store no longer does this scan when you open it and there doesn’t seem to be away to manually force a scan that I can see. 

Also when I have the update appstore apps option set under Software Updates via system preferences 

<img width="698" alt="image" src="https://user-images.githubusercontent.com/803618/82551589-63157780-9b58-11ea-912a-d776a8a5abfd.png">

It doesn’t seem to follow that rule when I manually force a software update by opening the screen.

UPDATE: I think  found away to force the app store app to list updates by using softwareupdate cli  with product keys and evaluation parameters but I need to experiment at the moment. 

<img width="921" alt="image" src="https://user-images.githubusercontent.com/803618/82562125-8cd89980-9b6c-11ea-99c2-b96b5af35593.png">

I still cannot force it to install and It doesn’t  seem to make any difference to mas update. but may be we can find  an alternative method to update apps that mas can use or fall back upon.

According to [ss64](https://ss64.com/osx/softwareupdate.html) softwareupdate should be showing something similar to the following but with Xcode14-5

> $ softwareupdate --list

     ! iPhoto-2.0
         iPhoto, 2.0, 34100K [recommended]
     ! iSync-1.0
         iSync, 1.0, 4840K [recommended]
     ! StuffItExpander7-7.0
         StuffIt Expander Security Update, 7.0, 4420K [recommended]

However, I am not getting  appstore apps in the results either even if they are listed in the app store as upgradable.

Very strange

**Comment by Sergong** [comment]
I have the same discrepancies, the left hand (softwareupdate) doesn't seem to be aware of updates scheduled for the App Store but in its history it does see which tool was installed by either the App Store (as well as other installers)... It seems quite a "mess"... Perhaps a case of "too many cooks in the kitchen" :)

**Comment by andrewcrook** [comment]
@Sergong  I am beginning to think it’s macOS.

**Comment by Sergong** [comment]
@andrewcrook it sure seems that way. Perhaps as someone else suggested, Apple is re-organising how this works but it is on the less important list...

**Comment by phatblat** [comment]
Should be fixed now in [1.8.1](https://github.com/mas-cli/mas/releases/tag/v1.8.1). @nottoseethesun  can you confirm?

**Comment by nottoseethesun** [comment]
I don't have macOS Catalina anymore, but I just checked in on Big Sur 11.2.2. and it works.  Thanks for fixing; we love `mas`!

**Comment by nottoseethesun** [comment]
@phatblat Please see my comment directly above.
