### ISSUE TITLE
🐛 [BUG] mas installs to wrong directory on second partition install

### ISSUE THREAD

**Issue by tiiiecherle** [mas-cli/mas#250]
## Your Environment

- `mas version`: 1.6.3
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 10.15.0 19A602

### mas Install Method

- [x] `brew install mas` (homebrew-core)

## Describe the Bug / To Reproduce

1.    Partition ssd/harddrive
2.    Install macOS on partition1 (macintosh_hd1)
3.    Install macOS on partition2 (macintosh_hd2)
4.    mount macintosh_hd1 when booted into macintosh_hd2
example-app1 is installed on macintosh_hd1, but not on macintosh_hd2
5.   try install example-app1 via mas when booted into macintosh_hd2
6.   mas thinks example-app1 is already installed
7.   force install example-app1 via mas when booted into macintosh_hd2
8.   mas installs app to macintosh_hd1

## Expected Behavior

mas should always install to the booted macOS installation.

## Feedback

Thanks a lot for this very nice project and all the work that is put into this.

Thanks for looking into the issue in advance.

Kind regards

**Comment by fharper** [comment]
It may be related to an issue I have while trying to install app on Catalina. I get this error

`Error: Download failed: The package is attempting to install content to the system volume.`

**Comment by tiiiecherle** [comment]
Unfortunately this issue still exists. As I am not a programmer I don't know if it is hard to fix. But for everyone working with a separate partition (internal or external) all apps on the main partition get overwritten instead of installing to the correct booted volume.

With the next macOS around the corner this will have an impact for the next half year where a lot of people will have to macOS installed on separate partitions.

It would be nice to see a fix for this or if it easier an option to specify the install volume. But I guess that the main usage will always be installing on the currently booted volume. An option would give even more flexibility.

Thanks a lot.

**Comment by Mazyod** [comment]
> Unfortunately this issue still exists. As I am not a programmer I don't know if it is hard to fix.

I was also interested to know ... So, I looked quickly through the code, and seems like mas uses a private Apple framework called "CommerceKit", and all it really does is pulls all installed software from using the singleton.

I would assume either mas is using the private framework wrong, but it's hard to tell since it's private and undocumented, or the private framework is limited and requires swizzling or other hacks to fix.

> With the next macOS around the corner this will have an impact for the next half year where a lot of people will have to macOS installed on separate partitions.

👋 That's what brought me here.

**Comment by tiiiecherle** [comment]
@Mazyod Thanks for the feedback and for looking into the code. For the given reasons I hope there will be a fix soon. The only workaround I found until now was to copy my mas apps install script to the booted macOS partition and unmount all partitions from other macOS installations. Then run the mas apps install script. This works, but is clearly only a workaround, not a solution.

**Comment by Mazyod** [comment]
Sure @tiiiecherle .. I honestly don't have THAT many Mac apps to bother with a workaround :) But the problem is intriguing, so I dug again and found more clues for someone who might tackle this .. Perhaps my future self.

https://github.com/mas-cli/mas/blob/master/PrivateFrameworks/StoreFoundation/ISStoreClient.h#L79

Basically, it is possible to initialize `ISStoreClient` with an application path, and then `SKSoftwareMap` with a store client, instead of relying on the singleton ... That _may_ work?

**Comment by tiiiecherle** [comment]
@Mazyod Thanks again for the feedback and for looking for a solution. Unfortunately I can not help regarding the code, sorry. Would be nice if you and @phatblat or another developer could pick it up for a fix.

Thanks in advance

**Comment by chris-araman** [comment]
This seems related to https://github.com/mas-cli/mas/issues/309#issuecomment-827966033.
