### ISSUE TITLE
`purchase` doesn't work on macOS 10.15+

### ISSUE THREAD

**Issue by ynp-repos** [mas-cli/mas#289]
## Your Environment

- `mas version`: 1.7.0
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 
    System Software Overview:

      System Version: macOS 10.15.5 (19F101)
      Kernel Version: Darwin 19.5.0

### mas Install Method

- [] `brew install mas` (homebrew-core)

## Describe the Bug

It seems that purchasing isn't working in Catalina. It's a brand new Macbook Pro 2020 with a fresh install of Homebrew and mas. 

Every time I try to purchase an app, specifically apps that aren't free, after using TouchID to buy the app, I get a "Purchase of this item is not currently available" error from the App Store and the download fails. This has happened for multiple apps, most recently Tweetbot 3.3.3 (`mas purchase 1384080005`). 

I can manually go to the app store and purchase it, but get this error when using mas. 

I was able to download and install XCode and Microsoft ToDo (both free apps), but any app that is not free does not work.  

## To Reproduce

1. Run `mas purchase 1384080005` in terminal 
2. When prompted enter Apple ID credentials in Mac App Store. 

## Expected Behavior
I would expect the App Store to ask me for TouchID or Password to confirm the purchase, and then begin to download. 

## Actual Behavior
See screenshot below for error. 

## Screenshots, Terminal Output
![Screen Shot 2020-07-03 at 6 01 58 PM](https://user-images.githubusercontent.com/67610641/86500526-58edb800-bd57-11ea-8bf0-6f4f3db2eebd.png)

```
$ mas purchase 1384080005
...
```

**Comment by chris-araman** [comment]
I can reproduce this on macOS 11.2.3 on an M1 MacBookPro.

**Comment by rgoldberg** [comment]
@mas-cli/contributors It looks like `mas purchase` worked as advertised all along, it's just that people misunderstood its usage due to poor naming.

I think that `mas purchase` has alway only supported "purchasing" free apps. @ynp-repos couldn't download non-free app, but was able to download free apps.

I think that, instead of reenabling `mas purchase`, we should modify `mas install` to automatically "purchase" unpurchased free apps when necessary. If we can figure out how to purchase non-free apps (I have a guess as to how that I'll try out later), then we should add a flag (maybe `--purchase`) to `mas install`. If someone tries to install a non-free app that wasn't previously purchased without including `--purchase`, we should output an error specifying the cost and the necessity to supply the `--purchase` flag.

To ensure that people don't spend more than they expect on an app, we could require user to specify a maximum cost they're willing to pay (like `--purchase 10.00USD` with a special `unlimited` value to specify no limit). We'd have to check how the store handles prices in different currencies. We would require that the specified currency match the currency expected by the MAS for the signed-in account for the purchase of the specified app.
