### ISSUE TITLE
Allow running mas as portable or installing it 

### ISSUE THREAD

**Issue by undergroundwires** [mas-cli/mas#326]
Thanks for creating and maintaining awesome tool ❤️

I wonder if there's a way to download and run a separate version `mas` and then deleting it without affecting existing installation of `mas`. I'd appreciate any suggestions on how to do that or feedback about "potential feature requests" part of my issue.

**Goal**

I'd like to be able download a specific version of the tool and use it in an isolated way. I'd possibly mess up existing installation of `mas` if I use `brew` or install it on the default location by running the installer.
 
**Potential feature requests**

-  Allow specification of installation path when I run `installer -pkg './mas.pkg' -target "/i-want-mas-to-be-here/"
- Distribution of portable version of mas without requiring any installer.

**Background/why**

I'll add some tweaks in  [privacy.sexy](https://github.com/undergroundwires/privacy.sexy) to remove preinstalled applications. And I'd like to distribute `mas` (download and run it on users' computers) to reinstall the applications (as a revert logic to removing them).

**Comment by chris-araman** [comment]
#350, if accepted, might move `mas` in the direction of a single portable binary. There are some questions left to answer before that's resolved, but it seems feasible.

**Comment by chris-araman** [comment]
> - Allow specification of installation path when I run `installer -pkg './mas.pkg' -target "/i-want-mas-to-be-here/"
> - Distribution of portable version of mas without requiring any installer.

Both options should be adddressed by #350.

**Comment by undergroundwires** [comment]
Hi @chris-araman , thanks for resolving this.

I tried with `installer -pkg` and it does not install it in the path of `-target` argument.

`which mas` gives me `/usr/local/bin/mas`

`pkgutil --pkg-info com.mphys.mas-cli` gives me empty location:

```txt 
package-id: com.mphys.mas-cli
version: 1.8.2
volume: /
location: 
install-time: 1621365685
```

**Questions**

- Is there any way to install it only in the folder I want?
- How can I uninstall it after running the `pkgutil`?

For the second point. I cannot run `mas` only in the portable release as it's unsigned. Also selecting right version per OS is much more complex. So I'd love to continue with installer pkg (first option).

I'm not very good at macOS so I might be thinking wrong here.

**Comment by chris-araman** [comment]
@undergroundwires, I don't think the `.pkg` is meant to do what you're trying to do. The target path is only a prefix to the installed binary's relative path `usr/local/bin/mas`. For instance, if you want to install to prefix `/opt/mySpecialPackageManager`, the absolute path to the binary would be `/opt/mySpecialPackageManager/usr/local/bin/mas`.

> `which mas` gives me `/usr/local/bin/mas`

That will depend on your `PATH`. Was `/tmp/mas/usr/local/bin` in your `PATH`?

The `.bottle.tar.gz` files in the 1.8.2 release are meant for the custom Homebrew tap, not general use by end users. That said, because of the way `mas` is built now, extracting the `mas` binary from those packages should allow for the portability you're looking for.

As before, the preferred way to install `mas` is via a package manager like Homebrew:
`brew install mas`
