### ISSUE TITLE
⬆️ Upgrade swift-format to 0.50400.0

### ISSUE THREAD

**Issue by phatblat** [mas-cli/mas#364]
Getting errors running `swift-format` on a box with only Xcode 12.5 installed.

```
↪ swift-format lint Package.swift
<unknown>:0:0: error: Unable to lint Package.swift: The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax
```

Looks like [0.50400.0](https://github.com/apple/swift-format/releases/tag/0.50400.0) is out which adds support for Swift 5.4. However, the Homebrew [swift-format formula update](https://github.com/Homebrew/homebrew-core/pull/76206) is pending Xcode 12.5 on the brew CI servers.

**Comment by chris-araman** [comment]
This is blocked on https://github.com/Homebrew/homebrew-core/pull/76206.

**Comment by chris-araman** [comment]
We can't actually support building with multiple versions of Swift (currently 5.3 and 5.4) and also depend on Homebrew's `swift-format`. Homebrew only supports "current" versions (https://github.com/Homebrew/homebrew-core/pull/76206 notwithstanding), but we need the `swift-format` version to match the version of the swift tools used to build `mas`.

I took a 🔪 at resolving this in #372, by depending instead of the `swift-format` package of the version that matches the Swift tools. Now `swift-format` should just work, no matter where it compiles, whether it compiles with swift 5.3 or 5.4.
