### ISSUE TITLE
Xcode.app 8.0 is required to build

### ISSUE THREAD

**Issue by huabin** [mas-cli/mas#48]
I install by command `brew install mas`, and get this error.

OS Version: 10.10.5 
Xcode Version: 7.2.1 (7C1002)
Homebrew Version: 1.0.4

Is there any way I can install this under Xcode 8.0?

**Comment by rodionovd** [comment]
The reason why `mas` requires Xcode 8 is that it's been upgraded to Swift 3.0 which is only officially supported in this version of Xcode. 

#### Workarounds

 1. Well, upgrade to Xcode 8.0 :-)
 2.  Instead of building `mas` from sources you could download a pre-built copy of the utility from [Releases](https://github.com/argon/mas/releases) and put it somewhere in your $PATH (e.g. into `/usr/local/bin`).

**Comment by hzb** [comment]
@rodionovd more logs to this issue

~ » brew install mas                                            HB@172-13-2-216
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

mas: A full installation of Xcode.app 8.0 is required to compile this software.
Installing just the Command Line Tools is not sufficient.
Xcode can be installed from the App Store.
Error: An unsatisfied requirement failed this build.

**Comment by rodionovd** [comment]
> OS Version: 10.10.5 

Sorry I missed this line in your original reports. Yes, Homebrew only provides pre-built copies of `mas` for OS X El Capitan (10.11) and Sierra (10.12) but you're on 10.10 so you're forced to compile the project yourself (using Xcode 8 which is not even compatible with 10.10).

**Comment by hzb** [comment]
ok, I know.
