### ISSUE TITLE
🐛 [BUG] Identifier 451108668 not found in store. Was expected to identify QQ

### ISSUE THREAD

**Issue by vstar37** [mas-cli/mas#629]
It seems that database is outdated?

**Comment by rgoldberg** [comment]
It's most likely an app that was removed from the Mac App Store.

Do you see the app in the Apple `App Store.app` interface? If not, then, for some reason, that app is no longer available.

Note that the same developer can release a new app with the same (or maybe just similar) name as the old one. Like, once app for versions 1.x, another for 2.x, etc. to be able to charge for new versions.

If you see it in your App Store, please provide the URL to the app page, which you can get by clicking on the share icon in the top right of the page, then "Copy Link`.

What country App Store do you intend to be signed in to?

In the new version of mas that was just released, 1.8.7, such warnings won't be displayed unless you use the `--verbose` flag. So, if you update, be sure to include that to investigate this.

**Comment by vstar37** [comment]
Thanks for you detailed reply, here is the link: https://apps.apple.com/tr/app/qq/id451108668?mt=12 , App Store region is Turkey

**Comment by rgoldberg** [comment]
@vstar37 Thanks for the info.

The problem is probably from the app not being available in the US App Store.

Have you updated mas to 1.8.7?

It should include a fix to use the current locale of your computer for the App Store region.

That obviously won't help if want to use the Turkey App Store, but you're in some locale other than Turkey.

Issue #75 is to allow users to manually specify the App Store region, but it isn't yet implemented.

It would be nicer if we could determine the region used for your `App Store.app`, but that information hasn't yet been found.

### Installing 1.8.7

1.8.7 is available from Homebrew.

I haven't tried the released bottles, but I built from the 1.8.7 source via Homebrew on an Intel.

**Comment by vstar37** [comment]
yeah 1.8.7 works properly.
