### ISSUE TITLE
Cannot build 1.8.7+ on macOS < 12.3 because `readlink` doesn't accept `-f` flag

### ISSUE THREAD

**Issue by cvortmann** [mas-cli/mas#636]
## Your Environment

- `mas version`: 1.8.6
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`):
```
Software:

    System Software Overview:

      System Version: macOS 11.7.10 (20G1427)
      Kernel Version: Darwin 20.6.0
      Time since boot: 7 days 23:14
```

### mas Install Method

- [x] `brew install mas` (homebrew-core)
- [ ] [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)
- [ ] `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)
- [ ] Built from source
  - Fork/branch: ? (e.g. mas-cli/main)
  - Xcode version: 10.?

## Describe the Bug

When running `brew upgrade` the process of upgrading from 1.8.6 to 1.8.7 fails due to `readlink: illegal option -- f`.

## To Reproduce

1. Call `brew upgrade` with `mas` version `1.8.6` installed.

## Expected Behavior

`mas` is upgrade to 1.8.7 successfully

## Actual Behavior

The process fails. `mas` is locked on 1.8.6.

### Full Output of `brew upgrade`

```bash
==> Upgrading mas
  1.8.6 -> 1.8.7
==> script/build
Last 15 lines from /Users/.../Library/Logs/Homebrew/mas/01.build:
2024-11-14 10:26:26 +0000

script/build

readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

**Comment by rgoldberg** [comment]
@cvortmann mas 1.8.7+ can only be built with macOS 12.5+ because it requires Xcode 14.2+ to be able to build Swift 5.7.1 (but the generated executables should be able to be run by macOS 10.13+).

The formula will be updated to reflect the aforementioned version requirements.

`-f` was added to `readline` in macOS 12.3, so its use is fine for any macOS that can build mas.

The normal way to install mas on older macOS versions for which Homebrew doesn't provide bottles is to use the mas custom tap:

```bash
# uninstall only necessary if you already have pre-1.8.7 mas installed via Homebrew
brew uninstall mas

brew install mas-cli/tap/mas
```

The currently  released 1.8.7 binaries, however, are only for Apple Silicon arm64, not for Intel x86_64.

The person working on the release process has been busy; If he cannot fix the released binaries & formula issues soon, I will look into it, but I am not experienced with either the old or the new release process.

**Comment by rgoldberg** [comment]
@cvortmann mas 1.8.8 was released.

The [Homebrew custom tap](https://github.com/mas-cli/homebrew-tap) now provides correct platform-specific binaries for both `arm64` & `x86_64`.

The `.pkg` installer from the [GitHub Release](https://github.com/mas-cli/mas/releases/v1.8.8) installs a Universal 2 binary.

**Comment by cvortmann** [comment]
> @cvortmann mas 1.8.8 was released.
> 
> The [Homebrew custom tap](https://github.com/mas-cli/homebrew-tap) now provides correct platform-specific binaries for both `arm64` & `x86_64`.
> 
> The `.pkg` installer from the [GitHub Release](https://github.com/mas-cli/mas/releases/v1.8.8) installs a Universal 2 binary.
> 
> Please let me know if it works for you. Thanks.

Installation with the following command went fine:

    brew install mas-cli/tap/mas
