### ISSUE TITLE
`install` for current user only

### ISSUE THREAD

**Issue by ShaneDelmore** [mas-cli/mas#72]
I just tried out MAS yesterday when setting up my new laptop (in combination with brew bundle).  Worked great and saved me a lot of time, thank you.  The only feature I was unable to find (if it even exists) is how to install applications for myself only, currently my fiance's account has all of my app store apps which is cluttering her applications with programming apps she has no use for.

**Comment by timsutton** [comment]
The Mac App Store provides no facility for installing applications to anywhere besides `/Applications`. It also uses bundle IDs to detect whether you already have something "installed", rather than paths.

I'm not sure you could, for example, move something newly installed out of /Applications into your own user dir without prompting for admin rights.

**Comment by rodionovd** [comment]
@timsutton is right: applications downloaded from the Mac App Store are available to all local users
