### ISSUE TITLE
Add ‘home’ [and maybe ‘open’ as an alias] command

### ISSUE THREAD

**Issue by danielbayley** [mas-cli/mas#96]
Similar to #26, which is being implemented in #55. Maybe this would need to be built on that work actually…

The URI scheme is basically just `macappstore://itunes.apple.com/{region}/app/{name}/id{id}`.

So usage could be for example `mas home 904280696`, which would call something like `macappstore://itunes.apple.com/{region}/app/things-3/id904280696?mt=12`.

**Comment by phatblat** [comment]
@danielbayley I'm looking into implementing this and have a question for you. What do you think about _both_ a `home` and `open` command? `home` would open the page in a browser and `open` would open the app page in the App Store app.

- home: https://itunes.apple.com/us/app/things-3/id904280696?mt=12
- open: `macappstore://itunes.apple.com/us/app/things-3/id904280696`

## sellerUrl

Another URL to consider is the `sellerUrl` attribute which appears to be the link behind the "Developer's Website" button.

### MAS Preview

![screen shot 2018-12-28 at 9 00 15 pm](https://user-images.githubusercontent.com/28851/50533687-caee9c80-0ae3-11e9-95d9-c1fffabe06a9.png)

### MAS App

"Website" link to the right of app description:
![screen shot 2018-12-28 at 9 05 18 pm](https://user-images.githubusercontent.com/28851/50533701-52d4a680-0ae4-11e9-9d69-9bf7735e05e5.png)

Below reviews and information:
![screen shot 2018-12-28 at 9 01 23 pm](https://user-images.githubusercontent.com/28851/50533688-d3df6e00-0ae3-11e9-97e1-10179bd6a073.png)


However, Things is a bad example because this ends up redirecting users to the Mac App Store.

1. `sellerUrl ` -> https://culturedcode.com/things/mac/
1. 302 redirect -> https://culturedcode.com/things/mac/appstore/
1. HTML "refresh" -> `<meta http-equiv="refresh" content="0; url=https://itunes.apple.com/us/app/things-3/id904280696?mt=12&amp;ls=1">`
1. Mac App Store Preview -> https://itunes.apple.com/us/app/things-3/id904280696?mt=12

In the case of [Notability](https://itunes.apple.com/us/app/notability/id736189492?mt=12) this `sellerUrl` points to http://www.gingerlabs.com which is a great example of an app site.

**Comment by danielbayley** [comment]
@phatblat I think separate `home` and `open` commands for those would work well… and maybe `sellerUrl` could be a third `vendor` (consistent with Homebrew parlance) command also?

**Comment by phatblat** [comment]
This is out now in [1.6.0](https://github.com/mas-cli/mas/releases/tag/v1.6.0)
